language: php

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

addons:
  apt:
    packages:
      - nginx
  hosts:
    - wordpress.dev

matrix:
  include:
  - php: 7.1
    env: WP_VERSION=4.8.1 WP_MULTISITE=1 PHPLINT=1 COVERAGE=1 BEHAT=1
  - php: 7.0
    env: WP_VERSION=4.8
  - php: 7.0
    env: WP_VERSION=4.7
  - php: 7.0
    env: WP_VERSION=4.6
  - php: 7.0
    env: WP_VERSION=4.5
  - php: 5.6
    env: WP_VERSION=4.8
  - php: 5.6
    env: WP_VERSION=4.7
  - php: 5.6
    env: WP_VERSION=4.6
  - php: 5.6
    env: WP_VERSION=4.5

before_install:
  - composer self-update
  - composer validate
  - phpenv config-rm xdebug.ini
  - export WH_DIR=$(pwd)
  - export WH_NGINX_DIR=/tmp
  - export WH_WORDPRESS_DIR="$WH_DIR/www/"
  - export WP_DEVELOP_DIR=/tmp/wordpress/

install:
  - composer install --prefer-dist --no-progress --no-dev
  - PATH=$PATH:./vendor/bin:./tests/bin/
  - export PATH

before_script:
  - ls -l ./vendor
  - if [[ "$BEHAT" == "1" ]]; then wordpress.sh wordpress root '' localhost $WP_VERSION; fi
  - if [[ "$BEHAT" == "1" ]]; then nginx.sh wordpress root '' localhost $WP_VERSION; fi
  - if [[ "$BEHAT" == "1" ]]; then selenium.sh wordpress root '' localhost $WP_VERSION; fi
  - export PLUGIN_SLUG=$(basename $(pwd))
  - echo $PLUGIN_SLUG
  - cd ..
  - ls /tmp/wordpress/src/
  - cp -r "$PLUGIN_SLUG" "/tmp/wordpress/src/wp-content/plugins/$PLUGIN_SLUG"

script:
  - if [[ "$BEHAT" == "1" ]]; then behat -dl; fi
  - if [[ "$PHPLINT" == "1" ]]; then find -L .  -path ./vendor -prune -o -name '*.php'
    -print0 | xargs -0 -n 1 -P 4 php -l; fi
  - if [[ -z "$CODECLIMATE_REPO_TOKEN" ]]; then COVERAGE="0"; fi
  - if [[ "$COVERAGE" == "1" ]]; then phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml;
    else phpunit -c phpunit.xml; fi
  - if [[ "$COVERAGE" == "1" ]]; then vendor/bin/test-reporter; fi

notifications:
  slack:
    secure: SUzXpLx+mr8fyKpzvOO8DXlmfVQhooePjCSz/JSLa1DdFgqX2kwWQsQWzDIVrpKMj+It1QtnZTr2B5rXV/C0isiwO30OYLS3+1srWQPHIuX0vVFfmJXmLw8mHPnaQB3DSdqTeH/t3ZyhUPvO3ZBScTQfg/WNxrJSL/j/VJVpuke0b/YgF5GNE/Bo44WDOxM4tkUj9GEeuYLTJG/xNbSo5kP6HxRR9wO5zumtlBkx/iIqw+QBY1x0n3P8QDdD5i1+mRyJz/2GB9ES0SC2ZA3aV1M4JLWQKwYgtznkBpBMARxFIkPBjPqPn+ojeIxrWM2W1dGaYK4WjAIgjFtk4/HrEigTYl96c69wztlWkI99qIp3y5KM49Inb+1Mwd0Ub9j8Rfzab9pnWb37jP4ctySRLf56S7SMFJ2XCDc/jirTVLK9SwgCS/og8LJ2FuFzmJjHS+6QCfqomYVOF9EnJCqontfCG7ks7VXrGXuMdfEyvZi/7OyHsecFk70XfGWA5f82FFRdVxJL5uFvCckC7EMhAGhA/XPuYv2FFSnU4eN9/prQsHxDUD/UGm2vu5JuCuEHJ43crzD1btGQAJOTDoTSH+fugK9ONlDLNaK96ojFq7aERgyl9bDz3QRlCjOGj5L0GfQbRhHy5hAYHVMwabUR/Wr3vsCq0lT8GgdM4I1wMtU=

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - kill -9 $(ps aux | grep 'selenium' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'java' | awk '{print $2}')
  - kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}')