language: php

cache:
  directories:
  - vendor
  - $HOME/.composer/cache

addons:
  apt:
    packages:
      - nginx
  hosts:
    - wordpress.dev

matrix:
  include:
  - php: 7.1
    env: WP_VERSION=latest BEHAT=1 PHPUNIT=1

before_install:
  - composer self-update
  - composer validate
  - phpenv config-rm xdebug.ini

  - export BIN_PATH="$CURRENT_DIR/bin"
  - export PATH=$PATH:./vendor/bin:$BIN_PATH
  - export CURRENT_DIR=$(pwd)
  - export NGINX_DIR=/tmp
  - export DB_NAME="wordpress"
  - export DB_USER="root"
  - export DB_PASS="root"
  - export DB_HOST="localhost"
  - export WP_DIR="/tmp/wordpress/"
  - export PLUGIN_DIR=$(pwd)
  - export PLUGIN_SLUG=$(basename $(pwd))

install:
  - echo $BIN_PATH
  - composer install --no-progress

before_script:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - if [[ "$BEHAT" == "1" ]]; then wordpress.sh $DB_NAME $DB_USER $DB_PASS $DB_HOST $WP_VERSION $WP_DIR; fi
  - if [[ "$BEHAT" == "1" ]]; then nginx.sh; fi
  - if [[ "$BEHAT" == "1" ]]; then selenium.sh; fi
  - cd ..
  - cp -r "$PLUGIN_SLUG" "$WP_DIR/wp-content/plugins/$PLUGIN_SLUG"
  - cd "$PLUGIN_SLUG"
  - wp plugin activate $PLUGIN_SLUG --path=$WP_DIR

script:
  - if [[ "$BEHAT" == "1" ]]; then behat; fi
  - if [[ "$PHPUNIT" == "1" ]]; then phpunit -c phpunit.xml; fi

notifications:
  email: false
  slack:
    secure: SUzXpLx+mr8fyKpzvOO8DXlmfVQhooePjCSz/JSLa1DdFgqX2kwWQsQWzDIVrpKMj+It1QtnZTr2B5rXV/C0isiwO30OYLS3+1srWQPHIuX0vVFfmJXmLw8mHPnaQB3DSdqTeH/t3ZyhUPvO3ZBScTQfg/WNxrJSL/j/VJVpuke0b/YgF5GNE/Bo44WDOxM4tkUj9GEeuYLTJG/xNbSo5kP6HxRR9wO5zumtlBkx/iIqw+QBY1x0n3P8QDdD5i1+mRyJz/2GB9ES0SC2ZA3aV1M4JLWQKwYgtznkBpBMARxFIkPBjPqPn+ojeIxrWM2W1dGaYK4WjAIgjFtk4/HrEigTYl96c69wztlWkI99qIp3y5KM49Inb+1Mwd0Ub9j8Rfzab9pnWb37jP4ctySRLf56S7SMFJ2XCDc/jirTVLK9SwgCS/og8LJ2FuFzmJjHS+6QCfqomYVOF9EnJCqontfCG7ks7VXrGXuMdfEyvZi/7OyHsecFk70XfGWA5f82FFRdVxJL5uFvCckC7EMhAGhA/XPuYv2FFSnU4eN9/prQsHxDUD/UGm2vu5JuCuEHJ43crzD1btGQAJOTDoTSH+fugK9ONlDLNaK96ojFq7aERgyl9bDz3QRlCjOGj5L0GfQbRhHy5hAYHVMwabUR/Wr3vsCq0lT8GgdM4I1wMtU=

after_script:
  # Tidy up after test run.
  # See https://github.com/travis-ci/travis-ci/issues/6861
  - if [[ "$BEHAT" == "1" ]]; then kill -9 $(ps aux | grep 'selenium' | awk '{print $2}'); fi
  - if [[ "$BEHAT" == "1" ]]; then kill -9 $(ps aux | grep 'java' | awk '{print $2}'); fi
  - if [[ "$BEHAT" == "1" ]]; then kill -9 $(ps aux | grep 'Xvfb' | awk '{print $2}'); fi