version: '3.1'
services:
  wp:
    image: mahype/wordpress:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DB: wp
      MYSQL_USER: root
      MYSQL_PASS: p4ssw0rd!
      WP_VERSION: 4.8.1
      WP_LOCALE: en_US
      WP_USER: admin
      WP_PASS: password
      WP_URL: wordpress.dev
      WP_INSTALL: "fresh"
      WP_PLUGINS: wordpress-importer
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - php
    networks:
      - testserver
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
      - ./bin/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      testserver:
        ipv4_address: 999.999.999.999
  php:
    image: mahype/phpbrew:latest
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress:/var/www/html
    environment:
      PHP_VERSION: "7.1.8"
    networks:
      - testserver
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
        - testserver
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    networks:
        - testserver
  behat:
    image: mahype/wordhat:latest
    volumes:
      - .:/src
    # Run a built-in web server for access to HTML reports
    ports:
      - 8081:8000
    entrypoint: "php -S 0.0.0.0:8000"
    networks:
      - testserver
  browser:
    image: selenium/standalone-chrome
    networks:
      - testserver
networks:
  testserver:
    ipam:
      config:
        - subnet: 10.221.50.0/24
volumes:
  dbdata:
