version: '3.1'
services:
  wp:
    container_name: docker_wpplugin_wp
    build:
        context: ./bin/docker/wordpress
    environment:
      MYSQL_HOST: db
      MYSQL_DB: wp
      MYSQL_USER: root
      MYSQL_PASS: p4ssw0rd!
      WP_VERSION: 4.8.1
      WP_PLUGINS: woocommerce wordpress-importer
      WP_LOCALE: de_DE
      WP_USER: admin
      WP_PASS: password
      WP_URL: localhost
      WP_INSTALL: "fresh"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - php
  web:
    container_name: docker_wpplugin_web
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./wordpress:/var/www/html
      - ./bin/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
      container_name: docker_wpplugin_php
      image: mahype/phpbrew:latest
      ports:
        - "9000:9000"
      volumes:
        - ./wordpress:/var/www/html
      environment:
        PHP_VERSION: "7.1.8"
  db:
    container_name: docker_wpplugin_db
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    container_name:
          docker_wpplugin_phpmyadmin
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: p4ssw0rd!
  behat:
      container_name:
        docker_wpplugin_behat
      hostname: behat
      image: docksal/behat
      volumes:
        - .:/src
      # Run a built-in web server for access to HTML reports
      ports:
        - 8081:8000
      entrypoint: "php -S 0.0.0.0:8000"
  browser:
      container_name: docker_wpplugin_browser
      image: selenium/standalone-chrome
volumes:
  wpdata:
  dbdata: