version: '3.1'
services:
  wp:
    image: mahype/wordpress:latest
    environment:
      MYSQL_HOST: db
      MYSQL_DB: wp
      MYSQL_USER: root
      MYSQL_PASS: my_password
      WP_VERSION: 4.9.6
      WP_LOCALE: en_US
      WP_USER: admin
      WP_PASS: password
      WP_URL: localhost
      WP_INSTALL: "fresh"
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - db
      - php
      - web
  web:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
  php:
    build: ./conf/php
    volumes:
     - ./conf/php/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: my_password
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
  phpmyadmin:
    depends_on:
      - db
      - web
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8888:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: my_password
  behat:
    image: mahype/wordhat:latest
    volumes:
      - ./:/src
    # Run a built-in web server for access to HTML reports
    ports:
      - 8081:8000
    entrypoint: "php -S 0.0.0.0:8000"
  browser:
    image: selenium/standalone-chrome
volumes:
  dbdata:
